/* FullName: Charalambos Philassides
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cafe_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author lishcp
 */
public class Cafe_Management_System extends javax.swing.JFrame {
    double [] drink = new double[5];
    double [] cakes = new double[7];
    double [] cost = new double[3];
    double [] i = new double[13];

    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPrint = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxCappucino = new javax.swing.JCheckBox();
        jCheckBoxIce_Cappuccino = new javax.swing.JCheckBox();
        jCheckBoxEspresso = new javax.swing.JCheckBox();
        jCheckBoxIced_Lattle = new javax.swing.JCheckBox();
        jCheckBoxLattle = new javax.swing.JCheckBox();
        jTextCappuccino = new javax.swing.JTextField();
        jText_Espresso = new javax.swing.JTextField();
        jText_Lattle = new javax.swing.JTextField();
        jText_Iced_Lattle = new javax.swing.JTextField();
        jText_Ice_Cappuccino = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jCheckCaffeeCake = new javax.swing.JCheckBox();
        jCheckBoxVelvet = new javax.swing.JCheckBox();
        jCheckBoxBoston = new javax.swing.JCheckBox();
        jCheckBoxBlackForest = new javax.swing.JCheckBox();
        jCheckBoxLagos = new javax.swing.JCheckBox();
        jTextFieldLagos = new javax.swing.JTextField();
        jTextVelvet = new javax.swing.JTextField();
        jTextFieldBlackForest = new javax.swing.JTextField();
        jTextBoston = new javax.swing.JTextField();
        jTextCaffeeCake = new javax.swing.JTextField();
        jCheckBoxKilburn = new javax.swing.JCheckBox();
        jTextFieldKilburn = new javax.swing.JTextField();
        jCheckBoxCarlton = new javax.swing.JCheckBox();
        jTextFieldCarlton = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabelCostDrinks = new javax.swing.JLabel();
        jLabelCostOfCake = new javax.swing.JLabel();
        jLabelServiceCharge = new javax.swing.JLabel();
        jlblCostOfDrinks = new javax.swing.JLabel();
        jlblCostOfCake = new javax.swing.JLabel();
        jlblServiceCharge = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButtonRecipt = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabelTax = new javax.swing.JLabel();
        jLabelSub_Total = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jlblCostOfDrinks1 = new javax.swing.JLabel();
        jlblCostOfDrinks2 = new javax.swing.JLabel();
        jlblCostOfDrinks3 = new javax.swing.JLabel();

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox16.setText("jCheckBox1");

        jCheckBox17.setText("jCheckBox2");

        jCheckBox18.setText("jCheckBox3");

        jCheckBox19.setText("jCheckBox4");

        jCheckBox20.setText("jCheckBox5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox20)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox16))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCheckBox16)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox17)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox18)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox19)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox20)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaPrint.setColumns(20);
        jTextAreaPrint.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPrint);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("CAFE MANAGEMENT SYSTEM");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        jLabel3.setText("☕");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBoxCappucino.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxCappucino.setText("Cappuccino");
        jCheckBoxCappucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCappucinoMouseClicked(evt);
            }
        });
        jCheckBoxCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCappucinoActionPerformed(evt);
            }
        });

        jCheckBoxIce_Cappuccino.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxIce_Cappuccino.setText("Ice Cappuccino");
        jCheckBoxIce_Cappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIce_CappuccinoMouseClicked(evt);
            }
        });
        jCheckBoxIce_Cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIce_CappuccinoActionPerformed(evt);
            }
        });

        jCheckBoxEspresso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxEspresso.setText("Espresso");
        jCheckBoxEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxEspressoMouseClicked(evt);
            }
        });
        jCheckBoxEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEspressoActionPerformed(evt);
            }
        });

        jCheckBoxIced_Lattle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxIced_Lattle.setText("Iced Lattle");
        jCheckBoxIced_Lattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIced_LattleMouseClicked(evt);
            }
        });
        jCheckBoxIced_Lattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIced_LattleActionPerformed(evt);
            }
        });

        jCheckBoxLattle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxLattle.setText("Lattle");
        jCheckBoxLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxLattleMouseClicked(evt);
            }
        });
        jCheckBoxLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLattleActionPerformed(evt);
            }
        });

        jTextCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCappuccino.setText("0");
        jTextCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCappuccinoActionPerformed(evt);
            }
        });

        jText_Espresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_Espresso.setText("0");
        jText_Espresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_EspressoActionPerformed(evt);
            }
        });

        jText_Lattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_Lattle.setText("0");
        jText_Lattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_LattleActionPerformed(evt);
            }
        });

        jText_Iced_Lattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_Iced_Lattle.setText("0");
        jText_Iced_Lattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Iced_LattleActionPerformed(evt);
            }
        });

        jText_Ice_Cappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_Ice_Cappuccino.setText("0");
        jText_Ice_Cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Ice_CappuccinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxIce_Cappuccino)
                    .addComponent(jCheckBoxCappucino, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxEspresso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxIced_Lattle, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxLattle, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_Lattle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_Iced_Lattle)
                    .addComponent(jText_Espresso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_Ice_Cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jTextCappuccino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCappucino)
                    .addComponent(jTextCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxIce_Cappuccino)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jText_Ice_Cappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEspresso)
                    .addComponent(jText_Espresso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxIced_Lattle)
                    .addComponent(jText_Iced_Lattle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxLattle)
                    .addComponent(jText_Lattle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 280));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckCaffeeCake.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckCaffeeCake.setText("Caffee Cake");
        jCheckCaffeeCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckCaffeeCakeMouseClicked(evt);
            }
        });

        jCheckBoxVelvet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxVelvet.setText("Rent Velvet Cake");
        jCheckBoxVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxVelvetMouseClicked(evt);
            }
        });

        jCheckBoxBoston.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxBoston.setText("Boston Cream Pie");
        jCheckBoxBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBostonMouseClicked(evt);
            }
        });

        jCheckBoxBlackForest.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxBlackForest.setText("Black Forest Cake");
        jCheckBoxBlackForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBlackForestMouseClicked(evt);
            }
        });

        jCheckBoxLagos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxLagos.setText("Lagos Chocolate Cake");
        jCheckBoxLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxLagosMouseClicked(evt);
            }
        });

        jTextFieldLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLagos.setText("0");
        jTextFieldLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLagosActionPerformed(evt);
            }
        });

        jTextVelvet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVelvet.setText("0");
        jTextVelvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVelvetActionPerformed(evt);
            }
        });

        jTextFieldBlackForest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBlackForest.setText("0");
        jTextFieldBlackForest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBlackForestActionPerformed(evt);
            }
        });

        jTextBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBoston.setText("0");
        jTextBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBostonActionPerformed(evt);
            }
        });

        jTextCaffeeCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCaffeeCake.setText("0");
        jTextCaffeeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCaffeeCakeActionPerformed(evt);
            }
        });

        jCheckBoxKilburn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxKilburn.setText("Kilburn Chocolate Cake");
        jCheckBoxKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxKilburnMouseClicked(evt);
            }
        });

        jTextFieldKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldKilburn.setText("0");
        jTextFieldKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKilburnActionPerformed(evt);
            }
        });

        jCheckBoxCarlton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBoxCarlton.setText("Carlton Hill Chocolate Cake");
        jCheckBoxCarlton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jCheckBoxCarltonMouseDragged(evt);
            }
        });

        jTextFieldCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCarlton.setText("0");
        jTextFieldCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCarltonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxBlackForest)
                            .addComponent(jCheckBoxBoston)
                            .addComponent(jCheckBoxVelvet)
                            .addComponent(jCheckCaffeeCake))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextBoston, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextCaffeeCake)
                            .addComponent(jTextVelvet)
                            .addComponent(jTextFieldBlackForest, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxLagos)
                            .addComponent(jCheckBoxKilburn))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldLagos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldKilburn))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCarlton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCaffeeCake, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckCaffeeCake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxVelvet))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBoston)
                    .addComponent(jTextBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBlackForest)
                    .addComponent(jTextFieldBlackForest, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxLagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxKilburn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCarlton)
                    .addComponent(jTextFieldCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 320, 280));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCostDrinks.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCostDrinks.setText("Cost Of Drinks");

        jLabelCostOfCake.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCostOfCake.setText("Cost Of Cake");

        jLabelServiceCharge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelServiceCharge.setText("Service Charge");

        jlblCostOfDrinks.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblCostOfDrinks.setForeground(new java.awt.Color(0, 0, 0));
        jlblCostOfDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDrinks.setText("0");
        jlblCostOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblCostOfCake.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblCostOfCake.setForeground(new java.awt.Color(0, 0, 0));
        jlblCostOfCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfCake.setText("0");
        jlblCostOfCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblServiceCharge.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblServiceCharge.setForeground(new java.awt.Color(0, 0, 0));
        jlblServiceCharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblServiceCharge.setText("1.50");
        jlblServiceCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCostDrinks)
                    .addComponent(jLabelServiceCharge)
                    .addComponent(jLabelCostOfCake))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblServiceCharge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCostOfCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCostDrinks)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCostOfCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCostOfCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelServiceCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblServiceCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 190));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButtonRecipt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonRecipt.setText("Recipt");
        jButtonRecipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReciptActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonTotal)
                .addGap(38, 38, 38)
                .addComponent(jButtonRecipt)
                .addGap(42, 42, 42)
                .addComponent(jButtonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTotal)
                    .addComponent(jButtonRecipt)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonExit))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 390, 90));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTax.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTax.setText("Tax");

        jLabelSub_Total.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSub_Total.setText("Sub Total");

        jLabelTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotal.setText("Total");

        jlblCostOfDrinks1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlblCostOfDrinks1.setForeground(new java.awt.Color(0, 0, 0));
        jlblCostOfDrinks1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDrinks1.setText("0");
        jlblCostOfDrinks1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblCostOfDrinks2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlblCostOfDrinks2.setForeground(new java.awt.Color(0, 0, 0));
        jlblCostOfDrinks2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDrinks2.setText("0");
        jlblCostOfDrinks2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblCostOfDrinks3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlblCostOfDrinks3.setForeground(new java.awt.Color(0, 0, 0));
        jlblCostOfDrinks3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDrinks3.setText("0");
        jlblCostOfDrinks3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblCostOfDrinks3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSub_Total)
                            .addComponent(jLabelTax))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCostOfDrinks2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jlblCostOfDrinks1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTax)
                    .addComponent(jlblCostOfDrinks1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSub_Total)
                    .addComponent(jlblCostOfDrinks2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jlblCostOfDrinks3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 390, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCappuccinoActionPerformed
        // TODO add your handling code here:
        jTextCappuccino.setText(null); 
        
    }//GEN-LAST:event_jTextCappuccinoActionPerformed

    private void jText_EspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_EspressoActionPerformed
        // TODO add your handling code here:
        jText_Espresso.setText(null);
         
    }//GEN-LAST:event_jText_EspressoActionPerformed

    private void jText_LattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_LattleActionPerformed
        // TODO add your handling code here:
        jText_Lattle.setText(null);      
    }//GEN-LAST:event_jText_LattleActionPerformed

    private void jText_Iced_LattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Iced_LattleActionPerformed
        // TODO add your handling code here:
        jText_Iced_Lattle.setText(null);   
    }//GEN-LAST:event_jText_Iced_LattleActionPerformed

    private void jText_Ice_CappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Ice_CappuccinoActionPerformed
        // TODO add your handling code here:
        jText_Ice_Cappuccino.setText(null);
    }//GEN-LAST:event_jText_Ice_CappuccinoActionPerformed

    private void jTextFieldLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLagosActionPerformed
        // TODO add your handling code here:
        jTextFieldLagos.setText(null);
    }//GEN-LAST:event_jTextFieldLagosActionPerformed

    private void jTextFieldBlackForestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBlackForestActionPerformed
        // TODO add your handling code here:
        jTextFieldBlackForest.setText(null);
    }//GEN-LAST:event_jTextFieldBlackForestActionPerformed

    private void jTextBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBostonActionPerformed
        // TODO add your handling code here:
        jTextBoston.setText(null);
    }//GEN-LAST:event_jTextBostonActionPerformed

    private void jTextVelvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVelvetActionPerformed
        // TODO add your handling code here:
        jTextVelvet.setText(null);
    }//GEN-LAST:event_jTextVelvetActionPerformed

    private void jTextCaffeeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCaffeeCakeActionPerformed
        // TODO add your handling code here:
        jTextCaffeeCake.setText(null);
    }//GEN-LAST:event_jTextCaffeeCakeActionPerformed

    private void jTextFieldKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKilburnActionPerformed
        // TODO add your handling code here:
        jTextFieldKilburn.setText(null);
    }//GEN-LAST:event_jTextFieldKilburnActionPerformed

    private void jTextFieldCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCarltonActionPerformed
        // TODO add your handling code here:
         jTextFieldCarlton.setText(null);
    }//GEN-LAST:event_jTextFieldCarltonActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here: RESET
       
        jTextBoston.setText(null);
        jTextCaffeeCake.setText(null);
        jTextCappuccino.setText(null); 
        jTextFieldBlackForest.setText(null);
        jTextFieldCarlton.setText(null);
        jTextFieldKilburn.setText(null);
        jTextFieldLagos.setText(null); 
        
/*private javax.swing.JLabel jLabelCostDrinks;
    private javax.swing.JLabel jLabelCostOfCake;
    private javax.swing.JLabel jLabelServiceCharge;
    private javax.swing.JLabel jLabelSub_Total;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotal;*/
        
        
        jlblServiceCharge.setText(null);
        jlblCostOfCake.setText(null);
        jlblCostOfDrinks.setText(null);
        jlblCostOfDrinks1.setText(null);
        jlblCostOfDrinks2.setText(null); 
        jlblCostOfDrinks3.setText(null);
         
        
        jTextVelvet.setText(null);
        jText_Espresso.setText(null);
        jText_Ice_Cappuccino.setText(null);
        jText_Iced_Lattle.setText(null);
        jText_Lattle.setText(null);
        
        jCheckBoxBlackForest.setSelected(false);
        jCheckBoxBoston.setSelected(false);
        jCheckBoxCappucino.setSelected(false);
        jCheckBoxCarlton.setSelected(false);
        jCheckBoxEspresso.setSelected(false);
        jCheckBoxIce_Cappuccino.setSelected(false);
        jCheckBoxIced_Lattle.setSelected(false);
        jCheckBoxKilburn.setSelected(false);
        jCheckBoxLagos.setSelected(false);
        jCheckBoxLattle.setSelected(false);
        jCheckBoxVelvet.setSelected(false);
        jCheckCaffeeCake.setSelected(false);
        jTextAreaPrint.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here: EXIT
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReciptActionPerformed
        // TODO add your handling code here: RECIPT
/*    private javax.swing.JTextField jText_Espresso;
    private javax.swing.JTextField jText_Ice_Cappuccino;
    private javax.swing.JTextField jText_Iced_Lattle;
    private javax.swing.JTextField jText_Lattle;*/
        
        drink[0] = Double.parseDouble(jText_Lattle.getText());
        drink[1] = Double.parseDouble(jText_Iced_Lattle.getText());
        drink[2] = Double.parseDouble(jText_Ice_Cappuccino.getText());
        drink[3] = Double.parseDouble(jText_Espresso.getText());
        drink[4] = Double.parseDouble(jTextCappuccino.getText());
        
        /*     
    private javax.swing.JTextField jTextFieldBlackForest;
    private javax.swing.JTextField jTextFieldCarlton;
    private javax.swing.JTextField jTextFieldKilburn;
    private javax.swing.JTextField jTextFieldLagos;
    private javax.swing.JTextField jTextBoston;
    private javax.swing.JTextField jTextCaffeeCake;*/

        cakes[0] = Double.parseDouble(jTextFieldBlackForest.getText());
        cakes[1] = Double.parseDouble(jTextFieldCarlton.getText());
        cakes[2] = Double.parseDouble(jTextFieldKilburn.getText());
        cakes[3] = Double.parseDouble(jTextFieldLagos.getText());
        cakes[4] = Double.parseDouble(jTextBoston.getText());
        cakes[5] = Double.parseDouble(jTextCaffeeCake.getText());
        cakes[6] = Double.parseDouble(jTextVelvet.getText());
        
        
        cost[0] = Double.parseDouble(jlblCostOfDrinks1.getText());
        cost[1] = Double.parseDouble(jlblCostOfDrinks2.getText());
        cost[2] = Double.parseDouble(jlblCostOfDrinks3.getText());
        
        
        

//========================     
//int ref = (refs);

int refs = 1325 + (int) (Math.random()*4238);

//=================================

       Calendar timer = Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       tTime.format(timer.getTime());
       SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
       tDate.format(timer.getTime());


//recipt print   
       
     jTextAreaPrint.append("\t\n Cafe Management System:\n\n" +
             "Reference:\t\t\t"  + refs +
             "\n========================================\t\t" +
             "\nLattle:\t\t\t" + drink[0] +
             "\nIced Lattle:\t\t\t" + drink[1] +
             "\nIce Cappuccino:\t\t" + drink[2] +
             "\nEspresso:\t\t\t" + drink[3] +
             "\nCappuccino:\t\t\t" + drink[4] +
                          "\n===========================================\t" +
                          "\nBlack Forest Cake:\t\t" + cakes[0] +
                          "\nCarlton Hill Chocolate Cake:\t\t" + cakes[1] +
                          "\nKilburn Chocolate Cake:\t\t" + cakes[2] +
                          "\nLagos Chocolate Cake:\t\t" + cakes[3] +
                          "\nBoston Cream Pie:\t\t" + cakes[4] +
                          "\nCaffee Cake:\t\t\t" + cakes[5] +
                          "\nRent Velvet Cake:\t\t" + cakes[6] +
                          "\n===========================================\t" +
                          "\nTax:\t\t\t" + cost[0] +
                          "\nSub Total:\t\t\t" + cost[1] +
                          "\nTotal:\t\t\t" + cost[2] +
                          "\n===========================================\t" +
                          "\nDate:" + tDate.format(timer.getTime()) +
                          "\t\tTime: " + tTime.format(timer.getTime()) +
             
             "\n\n\t\t Thank You\n"        

             );
       
    }//GEN-LAST:event_jButtonReciptActionPerformed

    private void jCheckBoxLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLattleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxLattleActionPerformed

    private void jCheckBoxLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxLattleMouseClicked
        // TODO add your handling code here:
        double cLattle = Double.parseDouble(jlblCostOfDrinks.getText());
        double Lattle = Double.parseDouble(jText_Lattle.getText());
        double iLattle = 1.99;
        
        if (jCheckBoxLattle.isSelected()){
        
            i[0] = (Lattle + cLattle)+iLattle;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostOfDrinks.setText(pDrink);
            jText_Lattle.setText(pDrink);
        }
    }//GEN-LAST:event_jCheckBoxLattleMouseClicked

    private void jCheckBoxCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCappucinoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxCappucinoActionPerformed

    private void jCheckBoxCappucinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCappucinoMouseClicked
        // TODO add your handling code here:
         double cCappuccino = Double.parseDouble(jlblCostOfDrinks.getText());
        double Cappuccino = Double.parseDouble(jTextCappuccino.getText());
        double iCappuccino = 2.39;
        
        if (jCheckBoxCappucino.isSelected()){
        
            i[0] = (Cappuccino + cCappuccino)+iCappuccino;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostOfDrinks.setText(pDrink);
            jTextCappuccino.setText(pDrink);
        }
    }//GEN-LAST:event_jCheckBoxCappucinoMouseClicked

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        // TODO add your handling code here:
        drink[0] = Double.parseDouble(jlblCostOfDrinks.getText());
        drink[1] = Double.parseDouble(jlblCostOfCake.getText());
        drink[2] = Double.parseDouble(jlblServiceCharge.getText());
        
        double cTotal1 = (drink[0]+drink[1]+drink[2]);
        String iTaxTotal = String.format("$ %.2f", cTotal1/100);
        jlblCostOfDrinks1.setText(iTaxTotal);
        
        double subTotal = (cTotal1);
        String iSubTotal = String.format("$ %.2f", cTotal1);
        jlblCostOfDrinks2.setText(iSubTotal);

        
        double allTotal = (cTotal1);
        String iTotal = String.format("$ %.2f", cTotal1 + (allTotal/100));
        jlblCostOfDrinks3.setText(iTotal);

                
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jCheckBoxIced_LattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIced_LattleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxIced_LattleActionPerformed

    private void jCheckBoxIced_LattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIced_LattleMouseClicked
        // TODO add your handling code here:
            double cIceLattle = Double.parseDouble(jlblCostOfDrinks.getText());
        double IceLattle = Double.parseDouble(jText_Iced_Lattle.getText());
        double iIceLattle = 1.99;
        
        if (jCheckBoxIced_Lattle.isSelected()){
        
            i[0] = (IceLattle + cIceLattle)+iIceLattle;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostOfDrinks.setText(pDrink);
            jText_Iced_Lattle.setText(pDrink);
        }
    }//GEN-LAST:event_jCheckBoxIced_LattleMouseClicked

    private void jCheckBoxEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEspressoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxEspressoActionPerformed

    private void jCheckBoxEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxEspressoMouseClicked
        // TODO add your handling code here:
         double cEspresso = Double.parseDouble(jlblCostOfDrinks.getText());
        double Espresso = Double.parseDouble(jText_Espresso.getText());
        double iEspresso = 2.99;
        
        if (jCheckBoxEspresso.isSelected()){
        
            i[0] = (Espresso + cEspresso)+iEspresso;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostOfDrinks.setText(pDrink);
            jText_Espresso.setText(pDrink);
        }
    }//GEN-LAST:event_jCheckBoxEspressoMouseClicked

    private void jCheckBoxIce_CappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIce_CappuccinoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxIce_CappuccinoActionPerformed

    private void jCheckBoxIce_CappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIce_CappuccinoMouseClicked
        // TODO add your handling code here:
        double cIce_Cappuccino = Double.parseDouble(jlblCostOfDrinks.getText());
        double Ice_Cappuccino = Double.parseDouble(jText_Ice_Cappuccino.getText());
        double iIce_Cappuccino = 1.99;
        
        if (jCheckBoxIce_Cappuccino.isSelected()){
        
            i[0] = (Ice_Cappuccino + cIce_Cappuccino)+iIce_Cappuccino;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostOfDrinks.setText(pDrink);
            jText_Ice_Cappuccino.setText(pDrink);}
      
    }//GEN-LAST:event_jCheckBoxIce_CappuccinoMouseClicked

    private void jCheckCaffeeCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckCaffeeCakeMouseClicked
        // TODO add your handling code here:
        double cCaffeeCake = Double.parseDouble(jlblCostOfCake.getText());
        double CaffeeCake = Double.parseDouble(jTextCaffeeCake.getText());
        double iCaffeeCake = 4.30;
        
        if (jCheckCaffeeCake.isSelected()){
        
            i[0] = (CaffeeCake + cCaffeeCake)+iCaffeeCake;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextCaffeeCake.setText(pCake);
        }
    }//GEN-LAST:event_jCheckCaffeeCakeMouseClicked

    private void jCheckBoxVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxVelvetMouseClicked
        // TODO add your handling code here:
         double cVelveCake = Double.parseDouble(jlblCostOfCake.getText());
        double VelveCake = Double.parseDouble(jTextVelvet.getText());
        double iVelveCake = 5.00;
        
        if (jCheckBoxVelvet.isSelected()){
        
            i[0] = (VelveCake + cVelveCake)+iVelveCake;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextVelvet.setText(pCake);
    }//GEN-LAST:event_jCheckBoxVelvetMouseClicked
    }
    
    
    private void jCheckBoxBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBostonMouseClicked
        // TODO add your handling code here:
        double cBostonCake = Double.parseDouble(jlblCostOfCake.getText());
        double BostonCake = Double.parseDouble(jTextBoston.getText());
        double iBostonCake = 5.00;
        
        if (jCheckBoxBoston.isSelected()){
        
            i[0] = (BostonCake + cBostonCake)+iBostonCake;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextBoston.setText(pCake);
    } 
    }//GEN-LAST:event_jCheckBoxBostonMouseClicked

    private void jCheckBoxBlackForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBlackForestMouseClicked
        // TODO add your handling code here:
        double cBlackForest = Double.parseDouble(jlblCostOfCake.getText());
        double BlackForest = Double.parseDouble(jTextFieldBlackForest.getText());
        double iBlackForest = 5.00;
        
        if (jCheckBoxBlackForest.isSelected()){
        
            i[0] = (BlackForest + cBlackForest)+iBlackForest;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextFieldBlackForest.setText(pCake);
    } 
    }//GEN-LAST:event_jCheckBoxBlackForestMouseClicked

    private void jCheckBoxLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxLagosMouseClicked
        // TODO add your handling code here:
        double cLagos = Double.parseDouble(jlblCostOfCake.getText());
        double Lagos = Double.parseDouble(jTextFieldLagos.getText());
        double iLagos = 5.00;
        
        if (jCheckBoxLagos.isSelected()){
        
            i[0] = (Lagos + cLagos)+iLagos;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextFieldLagos.setText(pCake);
    } 
    }//GEN-LAST:event_jCheckBoxLagosMouseClicked

    private void jCheckBoxKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxKilburnMouseClicked
        // TODO add your handling code here:
        double cburn = Double.parseDouble(jlblCostOfCake.getText());
        double burn = Double.parseDouble(jTextFieldKilburn.getText());
        double iburn = 5.00;
        
        if (jCheckBoxKilburn.isSelected()){
        
            i[0] = (burn + cburn)+iburn;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextFieldKilburn.setText(pCake);
    } 
    }//GEN-LAST:event_jCheckBoxKilburnMouseClicked

    private void jCheckBoxCarltonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCarltonMouseDragged
        // TODO add your handling code here:
         double cCarlton = Double.parseDouble(jlblCostOfCake.getText());
        double Carlton = Double.parseDouble(jTextFieldCarlton.getText());
        double iCarlton = 5.00;
        
        if (jCheckBoxCarlton.isSelected()){
        
            i[0] = (Carlton + cCarlton)+iCarlton;
            String pCake = String.format("%.2f", i[0]);
            jlblCostOfCake.setText(pCake);
            jTextFieldCarlton.setText(pCake);
    }
        
        
    }//GEN-LAST:event_jCheckBoxCarltonMouseDragged
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRecipt;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBoxBlackForest;
    private javax.swing.JCheckBox jCheckBoxBoston;
    private javax.swing.JCheckBox jCheckBoxCappucino;
    private javax.swing.JCheckBox jCheckBoxCarlton;
    private javax.swing.JCheckBox jCheckBoxEspresso;
    private javax.swing.JCheckBox jCheckBoxIce_Cappuccino;
    private javax.swing.JCheckBox jCheckBoxIced_Lattle;
    private javax.swing.JCheckBox jCheckBoxKilburn;
    private javax.swing.JCheckBox jCheckBoxLagos;
    private javax.swing.JCheckBox jCheckBoxLattle;
    private javax.swing.JCheckBox jCheckBoxVelvet;
    private javax.swing.JCheckBox jCheckCaffeeCake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCostDrinks;
    private javax.swing.JLabel jLabelCostOfCake;
    private javax.swing.JLabel jLabelServiceCharge;
    private javax.swing.JLabel jLabelSub_Total;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPrint;
    private javax.swing.JTextField jTextBoston;
    private javax.swing.JTextField jTextCaffeeCake;
    private javax.swing.JTextField jTextCappuccino;
    private javax.swing.JTextField jTextFieldBlackForest;
    private javax.swing.JTextField jTextFieldCarlton;
    private javax.swing.JTextField jTextFieldKilburn;
    private javax.swing.JTextField jTextFieldLagos;
    private javax.swing.JTextField jTextVelvet;
    private javax.swing.JTextField jText_Espresso;
    private javax.swing.JTextField jText_Ice_Cappuccino;
    private javax.swing.JTextField jText_Iced_Lattle;
    private javax.swing.JTextField jText_Lattle;
    private javax.swing.JLabel jlblCostOfCake;
    private javax.swing.JLabel jlblCostOfDrinks;
    private javax.swing.JLabel jlblCostOfDrinks1;
    private javax.swing.JLabel jlblCostOfDrinks2;
    private javax.swing.JLabel jlblCostOfDrinks3;
    private javax.swing.JLabel jlblServiceCharge;
    // End of variables declaration//GEN-END:variables
}
